### ISSUE TITLE
PSC not working

### ISSUE THREAD

**Issue by LuuKhoaHoc** [abgox/PSCompletions#1]
I followed you to add install PSC and Import PSC to PWSH, all thing ok but when i type psc and press space then tab. It's not working at well 
![image](https://github.com/abgox/PSCompletions/assets/93021204/2b132978-d12d-46c1-b7b7-07c9b5f1d9e6)
![image](https://github.com/abgox/PSCompletions/assets/93021204/0bc713d0-ecfb-4df1-9864-c268adb014eb)

**Comment by abgox** [comment]
- It's working fine for me.
- Restart PowerShell? See if it triggers a new module version update?
- If not, update the module manually , remove the git completion, and add it again.

![demo](https://github.com/abgox/PSCompletions/assets/131574323/7bcdae85-7af8-401e-ae2d-f33885979835)

**Comment by abgox** [comment]
![psc](https://github.com/abgox/PSCompletions/assets/131574323/5fb3c22b-aa78-4a11-973b-eb9633fd2bec)

**Comment by LuuKhoaHoc** [comment]
with me it triggered and told me update new version, and then it still not work. I deleted remove all module from before ver in Powershell module at Document then Reinstall that. It still not work. 
![image](https://github.com/abgox/PSCompletions/assets/93021204/3a6a0c8d-6bf4-4fb9-9490-ec941524ed90)
![image](https://github.com/abgox/PSCompletions/assets/93021204/9768c87f-a1b1-4b79-b7ff-9c68ff77e500)
![image](https://github.com/abgox/PSCompletions/assets/93021204/277cefb5-917d-4b30-9c7c-6b307a7b3d27)
![image](https://github.com/abgox/PSCompletions/assets/93021204/affacc64-88f9-4f2c-8331-c7236a9c46fc)
![image](https://github.com/abgox/PSCompletions/assets/93021204/f139b369-e4ee-47dc-b8e9-ad9db5b2e716)

**Comment by LuuKhoaHoc** [comment]
![image](https://github.com/abgox/PSCompletions/assets/93021204/4303473b-7d23-460f-abf6-e83e18e4eb82)
![image](https://github.com/abgox/PSCompletions/assets/93021204/265545c3-a39b-4ced-a6c8-9718b62f69d8)

**Comment by abgox** [comment]
You removed all the modules, and they included PSCompletions?
If not，You can try removing PSCompletions by running 'Uninstall-Module PSCompletions' and reinstall it.

**Comment by LuuKhoaHoc** [comment]
Yes, i did it, but im reinstall all of this but still now work

**Comment by LuuKhoaHoc** [comment]
Oh it get some error when i reinstall PSComplete
![image](https://github.com/abgox/PSCompletions/assets/93021204/7cc46a22-13d4-4d2b-bf06-9e05ee61a089)

**Comment by abgox** [comment]
I can't reappear  this bug.
We do the same thing, but the results are different.
![demo](https://github.com/abgox/PSCompletions/assets/131574323/4061f924-b2f9-4bd7-9cb0-b614f716d01e)

**Comment by abgox** [comment]
You can package all the files of the module and post it here, I will check it.

**Comment by abgox** [comment]
What's the latest situation?
If there are no other problems, the issue will be closed.

**Comment by LuuKhoaHoc** [comment]
Still error bro. It told me update to 3.0.3 then i press enter and this happend
![image](https://github.com/abgox/PSCompletions/assets/93021204/556cc605-4ffc-474e-a08a-3718bee420e7)

**Comment by abgox** [comment]
Are you using Windows Powershell? 
The problem is a lack of permissions.
You should follow the prompts and use -Scope or restart the command line with administrator privileges.

**Comment by LuuKhoaHoc** [comment]
Im using Window powershell bro, this my $NOTEPAD 
![image](https://github.com/abgox/PSCompletions/assets/93021204/fe6fea86-7680-4825-9755-ea0c545f190e)
It have any problem?

**Comment by abgox** [comment]
It's not their problem.
It's that in Windows PowerShell, you need to have enough permissions to install and update PowerShell modules smoothly.

**Comment by LuuKhoaHoc** [comment]
I just updated and this appear
![image](https://github.com/abgox/PSCompletions/assets/93021204/19c723e5-bac3-4e2d-bfad-32cf9ab8b61d)

**Comment by LuuKhoaHoc** [comment]
But still not working 
![image](https://github.com/abgox/PSCompletions/assets/93021204/a66d883a-a6f8-45b6-b6b3-83d580ea8689)

**Comment by abgox** [comment]
Maybe I know.
Do you try running the following command and see what the result is?
$PSCompletions.fn_download_list()

**Comment by LuuKhoaHoc** [comment]
![image](https://github.com/abgox/PSCompletions/assets/93021204/eb1fcf33-a8dc-4049-842e-f29463af5654)
That is result

**Comment by abgox** [comment]
I need you to change some code，Since I can't reappear the bug.
Change the 148-line throw statement to throw $_
![Snipaste_2023-12-10_20-27-50](https://github.com/abgox/PSCompletions/assets/131574323/eb0cab69-690e-4ada-95e3-a4a7eb544222)

**Comment by LuuKhoaHoc** [comment]
![image](https://github.com/abgox/PSCompletions/assets/93021204/360799eb-7a9c-4647-9bab-a1e7c2ad8bb8)
Still not work :(

**Comment by abgox** [comment]
What I need is the error message after the change.

**Comment by LuuKhoaHoc** [comment]
I didn't got an error message

**Comment by LuuKhoaHoc** [comment]
Are you have ultraview or something, help me fix that

**Comment by abgox** [comment]
It should be an unexpected error in the first initialization that caused something to be lost.
I need to check some directory structures.
Is it different from mine?
![1](https://github.com/abgox/PSCompletions/assets/131574323/131283a6-fad2-4c8a-8817-cc98994e52eb)
![2](https://github.com/abgox/PSCompletions/assets/131574323/dd103f82-ea6d-4c1c-a1ec-60818c26a3f1)
![3](https://github.com/abgox/PSCompletions/assets/131574323/62e0122c-c29e-452a-acd4-c3abbc1ed73c)
![4](https://github.com/abgox/PSCompletions/assets/131574323/ca4c9c55-750d-401d-a44d-c613df09bfdc)

**Comment by LuuKhoaHoc** [comment]
![image](https://github.com/abgox/PSCompletions/assets/93021204/1827150a-0767-401e-9a2c-e99c431588ea)
![image](https://github.com/abgox/PSCompletions/assets/93021204/d8a81218-b2bb-4d20-971d-9c3581143fa4)
![image](https://github.com/abgox/PSCompletions/assets/93021204/22d7d7e2-1f4a-40c4-b4e7-9d20e71022bd)
![image](https://github.com/abgox/PSCompletions/assets/93021204/fa6e22e1-b0df-4cf4-82ac-2962b6a8503b)
We are same bro

**Comment by abgox** [comment]
I'm using Windows Terminal.
But that shouldn't be a problem, and I tested it on several other computers and  PowerShell under Linux.

**Comment by LuuKhoaHoc** [comment]
![image](https://github.com/abgox/PSCompletions/assets/93021204/36335f28-2d6b-4f5c-84e0-cf2fb1705a59)
 I try to remove PSComplete and i still can add git after that

**Comment by abgox** [comment]
Try to run 'Uninstall-Module PSCompletions'?

**Comment by LuuKhoaHoc** [comment]
Ok i just uninstall it and that work. Let me try reinstall

**Comment by abgox** [comment]
What's the latest situation?
After my testing, when there are some old versions in a module, it makes the install, uninstall, and remove commands invalid.
I suggest you just delete the PSCompletions folder and then reinstall it.

**Comment by LuuKhoaHoc** [comment]
still not work bro :(. I alse delete the PSCompletions folder for every time when i use Remove-Module not work

**Comment by abgox** [comment]
Now, after you delete it, can you restart powershell and use psc command normally?
Do you get errors like I do?
![Snipaste_2023-12-10_21-40-40](https://github.com/abgox/PSCompletions/assets/131574323/19a81254-d7f5-4b2c-a8b4-0322334d599b)

**Comment by LuuKhoaHoc** [comment]
Yes, that sure bro

**Comment by abgox** [comment]
If you reinstall the module now, it won't report the previous error, just it don't work?

**Comment by LuuKhoaHoc** [comment]
![image](https://github.com/abgox/PSCompletions/assets/93021204/998fc627-8051-4e8e-a303-b8a72cc9eb27)

**Comment by LuuKhoaHoc** [comment]
![image](https://github.com/abgox/PSCompletions/assets/93021204/376ed6b8-6738-480a-89e0-e4a4aec37083)

**Comment by LuuKhoaHoc** [comment]
![image](https://github.com/abgox/PSCompletions/assets/93021204/e19c1c97-2bf7-4007-aeb6-8aef9c142eb2)
![image](https://github.com/abgox/PSCompletions/assets/93021204/26e6d895-e358-4b68-926e-5dfa22c047d4)
![image](https://github.com/abgox/PSCompletions/assets/93021204/7fe99266-d26b-4f19-96c9-8b820f0d7c0b)
Full height of report after reinstall PSCompletion

**Comment by abgox** [comment]
That's the problem here, but it seems that it will only appear on your computer
![Snipaste_2023-12-10_21-49-11](https://github.com/abgox/PSCompletions/assets/131574323/5c882506-5d09-4477-be41-58e677423aa3)

Try to run the following command and see the result:
$PSCompletions.fn_get_config()

**Comment by abgox** [comment]
It should output :
![Snipaste_2023-12-10_21-52-45](https://github.com/abgox/PSCompletions/assets/131574323/0ab270ce-de18-4298-94c1-5b30008dd665)

**Comment by LuuKhoaHoc** [comment]
![image](https://github.com/abgox/PSCompletions/assets/93021204/56b0366e-0ed2-41f5-bb3a-4a80d878fea7)
from me

**Comment by abgox** [comment]
Unzip this core to replace the core folder in PSCompletions.
[core.zip](https://github.com/abgox/PSCompletions/files/13628043/core.zip)

**Comment by abgox** [comment]
I simulated your environment and found that when I import it, my psc didn't work anymore
![Snipaste_2023-12-10_22-23-11](https://github.com/abgox/PSCompletions/assets/131574323/292cff6a-7acb-4bef-9944-4fd15ba27b01)

**Comment by LuuKhoaHoc** [comment]
Oh god, that why, i will try now

**Comment by LuuKhoaHoc** [comment]
It work bro, thank a lot. <3 Im really happy. Thank you very much 🥰😭.

**Comment by abgox** [comment]
For their conflicts, I'll deal with them in the next release.
I hope PSCompletions can help your work.

**Comment by LuuKhoaHoc** [comment]
Thank you very much, it help a lot. I will close issue after this comment

**Comment by csxian2012** [comment]
遇到同样的问题。跟随这个教程跑了一遍，然后才发现大佬的PSCompletions。再使用PSCompletions后tab展示的内容类似上面的反馈，请问大佬，是不是同样的原因导致冲突了，如何消除这个冲突
![image](https://github.com/abgox/PSCompletions/assets/37734145/3e840d4c-77f9-4e1f-a5d2-9710d63d85dd)

**Comment by abgox** [comment]
使用的平台呢？Windows? Linux?
使用的是 Powershell 还是 Windows Powershell?
有无报错？

**Comment by csxian2012** [comment]
没有报错，除了tab不行，其他看起来都没问题，下面是我的脚本文件。
之前代码中有Set-PSReadlineKeyHandler -Key Tab -Function MenuComplete。
我尝试了Remove-PSReadlineKeyHandler -Key Tab，但是也没恢复正常

![image](https://github.com/abgox/PSCompletions/assets/37734145/cea88f81-182a-4454-937c-1294c5041118)

**Comment by csxian2012** [comment]
平台是window 10，工具是Windows terminal，terminal中配置的是power shell

**Comment by abgox** [comment]
Powershell的版本呢？
![Snipaste_2023-12-14_11-14-54](https://github.com/abgox/PSCompletions/assets/131574323/abfba40f-709a-4eb3-b08f-fd6e996b5a83)

**Comment by abgox** [comment]
我这里的测试是完全没有问题的，你的配置文件是否还包含了其他的内容，我需要看一看你完整的配置文件
![Snipaste_2023-12-14_11-17-17](https://github.com/abgox/PSCompletions/assets/131574323/e5703eff-764b-4557-b7df-f593211e0c04)
![Snipaste_2023-12-14_11-18-40](https://github.com/abgox/PSCompletions/assets/131574323/cd1e2b95-b7ba-4217-8edd-e0026343e950)

**Comment by csxian2012** [comment]
![image](https://github.com/abgox/PSCompletions/assets/37734145/bae42dce-8959-4c40-b135-aa806b8ee987)
power shell版本看起来是有些低。

完整代码如下，其他代码是用于展示当前分支的，不会影响提示
function Write-BranchName () {
    try {
        $branch = git rev-parse --abbrev-ref HEAD
        if ($branch -eq "HEAD") {
            # we're probably in detached HEAD state, so print the SHA
            $branch = git rev-parse --short HEAD
            Write-Host " ($branch)" -ForegroundColor "red"
        }
        else {
            # we're on an actual branch, so print it
            Write-Host " ($branch)" -ForegroundColor "blue"
        }
    } catch {
        # we'll end up here if we're in a newly initiated git repo
        Write-Host " (no branches yet)" -ForegroundColor "yellow"
    }
}

function prompt {
    $base = "PS "
    $path = "$($executionContext.SessionState.Path.CurrentLocation)"
    $userPrompt = "$('>' * ($nestedPromptLevel + 1)) "
    Write-Host "`n$base" -NoNewline
    if (Test-Path .git) {
        Write-Host $path -NoNewline -ForegroundColor "green"
        Write-BranchName
    }
    else {
        # we're not in a repo so don't bother displaying branch name/sha
        Write-Host $path -ForegroundColor "green"
    }
    return $userPrompt
}

$OutputEncoding = [console]::InputEncoding = [console]::OutputEncoding = New-Object System.Text.UTF8Encoding

# Shows navigable menu of all options when hitting Tab
# Set-PSReadlineKeyHandler -Key Tab -Function MenuComplete

# Autocompletion for arrow keys
# Set-PSReadlineKeyHandler -Key UpArrow -Function HistorySearchBackward
# Set-PSReadlineKeyHandler -Key DownArrow -Function HistorySearchForward

# auto suggestions
Import-Module PSCompletions
Set-PSReadLineOption -PredictionSource History
Import-Module PSReadLine

**Comment by abgox** [comment]
它实际上是windows 内置的 Windows Powershell，而不是 Powershell，我指的Powershell是能跨平台的那个版本。
不过在 Windows Powershell 中也是可以使用的
我复制了你的配置文件，在我的 Windows Powershell 中也是可以使用的
![Snipaste_2023-12-14_11-29-13](https://github.com/abgox/PSCompletions/assets/131574323/9fa3b4c4-46e5-48f8-baa0-dcfb81880787)
![Snipaste_2023-12-14_11-31-09](https://github.com/abgox/PSCompletions/assets/131574323/72f7c8a4-aba5-4821-9f08-9a3bda3df2e1)

**Comment by abgox** [comment]
不是环境的问题，模块也没有报错，且我模拟了你相同的环境，也没有问题，但在你的电脑上使用它出现了问题，这就有些玄学了。
建议你试试 Powershell 吧

**Comment by csxian2012** [comment]
好的，我再测试下，假如可以找到原因我再反馈下，感谢。

**Comment by csxian2012** [comment]
应该是版本问题，系统自带的power shell好像最高只到5.0，不知道怎么弄出来的，可以提示了，但是会有个确认操作。
![image](https://github.com/abgox/PSCompletions/assets/37734145/088accaa-a687-46ae-8712-28917b99e93a)

https://github.com/abgox/PSCompletions/assets/37734145/ec9ce687-d286-4e64-8da0-382a30c98509

**Comment by abgox** [comment]
确定操作是正常的，这是默认行为，因为补全数量过多。
我还是更建议使用powershell，powershell可以使用更好用的新补全菜单 UI。当然，全凭自己喜好。
既然问题解决，这个 issue 我就关闭了
