### ISSUE TITLE
PSCompletions are not working

### ISSUE THREAD

**Issue by soredake** [abgox/PSCompletions#10]
3.2.6 version is installed, pressing space + tab is doing nothing. I have installed [pwsh from microsoft store](https://apps.microsoft.com/detail/9mz1snwt0n5d?hl=en-us&gl=UA) if this matter.

No such problem with Windows PowerShell.

**Comment by abgox** [comment]
Is there an error here?

**Comment by soredake** [comment]
None.

**Comment by abgox** [comment]
- When you type `psc` , does the following output appear?
![demo](https://github.com/abgox/PSCompletions/assets/131574323/62e9477c-b4f9-48f1-a64d-5d1fefa7cb51)

**Comment by soredake** [comment]
Yes.

![image](https://github.com/abgox/PSCompletions/assets/5204968/eb191357-1b11-4312-866b-41950cf7909e)

**Comment by abgox** [comment]
- I can't repeat the problem in my computer.
- I uninstalled `pwsh` and  `PSCompletions` , then I reinstall.
- They're all working fine.

---
Here I'll give you some advice:
- You can only import `PSCompletions` to test, excluding the effects of other modules.
- You should try reinstalling.

**Comment by soredake** [comment]
> You can only import `PSCompletions` to test, excluding the effects of other modules.

I think I found the culprit, it's `CompletionPredictor` module, I'll report this issue to them.

**Comment by abgox** [comment]
- If you want them to be conflict-free, you can temporarily use powershell  build-in completion menu by running the follow command.
- `psc ui menu powershell`
