### ISSUE TITLE
新UI不对齐

### ISSUE THREAD

**Issue by Arama-Vanarana** [abgox/PSCompletions#11]
新版的补全ui似乎没有对齐, 这是正常的吗:
![image](https://github.com/abgox/PSCompletions/assets/122252361/2bf14189-6cb8-4cbb-acce-1048c268c886)

**Comment by abgox** [comment]
在我这里一切正常
![image](https://github.com/abgox/PSCompletions/assets/131574323/788197bb-a7a0-43c7-9e01-7a777eb288ac)

**Comment by abgox** [comment]
- 试试 `psc update psc` 强制更新一下补全
- 添加一下其他的补全看看,是否提示信息都对不齐

**Comment by abgox** [comment]
问题解决了吗？

**Comment by Arama-Vanarana** [comment]
![image](https://github.com/abgox/PSCompletions/assets/122252361/aa190986-eee0-4515-8650-ec33ed823f5d)
没有

**Comment by abgox** [comment]
1. 打印 `$PSVersionTable` 这个变量看看 PowerShell 版本信息
2. 把 `$Profile` 这个变量指向的 Powershell 配置文件里的内容暂时清空，只导入 PSCompletions 模块看看

**Comment by Arama-Vanarana** [comment]
PS C:\Users\Arama> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.2
PSEdition                      Core
GitCommitId                    7.4.2
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

$Profile变量文件里是空的

**Comment by Arama-Vanarana** [comment]
我知道为啥了, 我在profile.ps1里加了一个`$OutputEncoding = [console]::InputEncoding = [console]::OutputEncoding = New-Object System.Text.UTF8Encoding`是utf8编码的问题

**Comment by abgox** [comment]
- 实际上，是 `[console]::OutputEncoding = New-Object System.Text.UTF8Encoding`  导致了问题
- 那你就不能修改 `[console]::OutputEncoding` 的值了

**Comment by abgox** [comment]
- 顺便问一句，`[console]::OutputEncoding = New-Object System.Text.UTF8Encoding`
- 为什么要设置它呢？是有什么作用吗？

**Comment by Arama-Vanarana** [comment]
我看网上说这个能设置utf-8我就设置了(

**Comment by Arama-Vanarana** [comment]
我还是老老实实用wsl吧

**Comment by abgox** [comment]
- 这个问题，倒是可以修复一下
- 我在下一个版本里修复一下吧
- 不过修复完成后，你必须把 `$OutputEncoding = [console]::InputEncoding = [console]::OutputEncoding = New-Object System.Text.UTF8Encoding` 这条语句放在 `Import-Module PSCompletions` 后

**Comment by Arama-Vanarana** [comment]
好
