### ISSUE TITLE
自动更新Bug

### ISSUE THREAD

**Issue by Arama-Vanarana** [abgox/PSCompletions#12]
![image](https://github.com/abgox/PSCompletions/assets/122252361/32ab5134-d0ab-455c-a728-8c1c3ed34583)
更新回退, 按下Enter后提示
![image](https://github.com/abgox/PSCompletions/assets/122252361/0675bc9b-6e83-4c7c-aaa2-d1441a5a8672)

**Comment by abgox** [comment]
1. 我这里没有这样的问题，你应该按下除 `Enter` 键的任意键取消更新
2. 然后运行  `psc config module_update 1`

**Comment by Arama-Vanarana** [comment]
没有提示了, 蟹蟹
