### ISSUE TITLE
team up with argc-completions

### ISSUE THREAD

**Issue by Konfekt** [abgox/PSCompletions#13]
Hello,

for those coming from [argc-completions](https://github.com/sigoden/argc-completions) a quick comparison would be helpful.
Can the projects build up on each other?

**Comment by abgox** [comment]
- The completions of `PSCompletions` are not automatically generated, it need json file. 
- These json file must be defined in advance and added locally.

**Comment by Konfekt** [comment]
Thank you. It seems that `PSCompletions` is also more native, being a PS1 script, whereas `argc` needs an additional exe and MSYS2 at least for installation

**Comment by abgox** [comment]
- The PSCompletions module is now based on a json file.
- You should say what completions you need to say, and I'll consider add it.
- Maybe I can take a look at how `argc` generates completion, which allow me to quickly generate some json file that matches the `PSCompletions`.

- I'm also writing the document of `PSCompletions`, which makes it possible for others to work with me to add/update completions.

**Comment by Konfekt** [comment]
> You should say what completions you need to say, and I'll consider add it.

Maybe consider these: https://github.com/se35710/scoop-main/blob/master/bucket/coreutils.json

I am mainly thinking of replicating the Git Bash experience

**Comment by abgox** [comment]
- These commands do not require completion.
- I think you just need to set the alias and function.

**Comment by Konfekt** [comment]
More comprehensive would be https://github.com/bmatzelle/gow/tree/master/bin

**Comment by abgox** [comment]
- In `v5.1.0` , `PSCompletions` can be combined with `argc-completions`.
- For detail:  https://pscompletions.pages.dev/FAQ/#pscompletions-and-argc-completions

**Comment by Konfekt** [comment]
Maybe these additional commands deserve mention in the [README](https://github.com/abgox/PSCompletions?tab=readme-ov-file#available-completions-list)
