### ISSUE TITLE
增强 `enter_when_single` 

### ISSUE THREAD

**Issue by F-park** [abgox/PSCompletions#15]
当命令只含单一子命令和它的别名时，也应该自动补全。

![image](https://github.com/user-attachments/assets/f08626de-180c-4f40-99a7-dedbb64063e3)

**Comment by abgox** [comment]
- 这没有太大意义，大多数情况下，别名长得不怎么像，比如 `add`/`install` ，`rm`/`remove`，`list`/`ls`等
- `update`/`upgrade` 前缀有两个字符相同，但也只需要输入三个字符就可以被过滤掉，输入成本并不高
- 而且，目前由 json 文件解析出来的补全项，在 UI 渲染阶段是无法获取到它们的关系的，这需要添加额外的逻辑，延长 UI 渲染的时间
