### ISSUE TITLE
增加对 pwsh 和 powershell 的补全

### ISSUE THREAD

**Issue by F-park** [abgox/PSCompletions#16]
## 需求分析

`pwsh` 最新预览版为 7.5
windows 自带的 `powershell` 版本为 5.1

## 命令参考

https://learn.microsoft.com/zh-cn/powershell/module/microsoft.powershell.core/about/about_pwsh?view=powershell-7.5
https://learn.microsoft.com/zh-cn/powershell/module/microsoft.powershell.core/about/about_pwsh?view=powershell-7.5&viewFallbackFrom=powershell-5.1

**Comment by abgox** [comment]
- `pwsh` 和 `powershell` 本身是具备补全的
- 如果要添加的话，以 `PSCompletions` 的运行机制，需要给其中的每一个命令添加 json 定义文件来支持补全，且灵活度没有官方内置的补全灵活，暂时不考虑添加
- 如果你愿意，你可以 fork 仓库，创建 PR

**Comment by F-park** [comment]
请问 `pwsh` 怎么启用内置的补全呢，我的 pwsh 7.4 无法用 Tab 键补全，找了一天也没找到相关文档，甚至按 F1 键还找不到帮助。
![image](https://github.com/user-attachments/assets/165758ad-5d87-4c14-a74d-40cffc666bbc)

**Comment by abgox** [comment]
- `Set-PSReadLineKeyHandler Tab MenuComplete` 这句命令放在 `$profile` 中就可以了
- 不过如果你在 `$profile` 中引入了 `PSCompletions` 的话，就不需要，因为 `PSCompletions` 内部就使用了这个命令

**Comment by abgox** [comment]
- `Set-PSReadLineOption -PredictionSource History`
- `Set-PSReadLineOption -PredictionViewStyle ListView`
- 这两条命令建议添加，体验还不错

**Comment by F-park** [comment]
我的 `$profile` 里有 `Set-PSReadLineKeyHandler Tab MenuComplete` 和 `Set-PSReadLineOption -PredictionSource History` 这两条命令，但依旧无法显示补全菜单

![image](https://github.com/user-attachments/assets/d66a9d40-ce1f-4847-9702-430a36cd609c)

内置命令是正常的

![image](https://github.com/user-attachments/assets/beed1cfd-205c-47e3-a051-06b637682f48)

我早上才用 `scoop` 重装过 `pwsh`，应该不是 `pwsh` 的问题

**Comment by abgox** [comment]
- 你指的是 `pwsh` 这个命令的补全?那倒是没有内置补全
- 我指的补全，就是 `pwsh` 内置的这些命令(如 `Get-Command`)的补全

**Comment by F-park** [comment]
我指的是前者，那应该称为 `pwsh_cli` ? 我没表达好，不好意思。

**Comment by abgox** [comment]
- 如果指的是这个的话，`PSCompletions` 确实也可以去添加它，包括内置命令也可以
- 但是这就很随缘了，因为没有其他人帮我去定义这些 json，就完全看我的时间了，不过现在的话，我很少有时间去定义这些 json了，特别是像 `git` 那样的几千行的 json

**Comment by F-park** [comment]
是否可以用 powershell 脚本或 python 脚本自动提取命令的中英帮助文本，然后自动解析成 json 呢，然后用 github actions 定时执行，类似 scoop bucket 的操作，不过可能只能提取特定框架的。

**Comment by abgox** [comment]
- scoop 的 json 也是先定义了，然后才能通过 github actions 去自动解析
- 而且 scoop 的自动解析，只需要去获取到软件的新版本以及新地址就好了，这其实规律很固定，就比较简单
- 但是 `PSCompletions` 如果是去解析帮助文本的话，各种 cli 命令的帮助又各有各的特点，要使用一个脚本来实现解析比较麻烦
- 实现的可能性是有的，但是我短时间不会去做这个事，我的时间很有限，有其他更重要的事情
