### ISSUE TITLE
[Enhancement] 为 `psc` 的 `add` 和 `rm` 子命令增加通配符选项

### ISSUE THREAD

**Issue by F-park** [abgox/PSCompletions#17]
## 原因

现在 `add` 和 `rm` 得一个个增加/移除补全，太麻烦了，应该加入通配符交给代码处理。

### `psc add *` 

用 `Get-Command` 逐个检查补全列表，本地有这个命令则增加补全

### `psc rm *` 

将删除所有已增加补全

**Comment by abgox** [comment]
- 我不确定当大量添加 `Register-ArgumentCompleter` 是否会导致 PowerShell 本身的首次加载速度变慢，所以没有添加通配符，更希望根据自己的需求，精确的添加补全
- 如果你确实需要批量的添加或删除所有补全，你可以使用以下命令
   - 添加所有补全: `$PSCompletions.list | ForEach-Object { psc add $_  }`
   - 移除所有补全: `$PSCompletions.list | ForEach-Object { psc rm $_  }`

**Comment by abgox** [comment]
- 下个版本会添加这两个命令

**Comment by F-park** [comment]
8cb685fe8b7738b94dbe010656d568e916285ad6 中完成
