### ISSUE TITLE
[Request]: 为什么这儿的代码版本和powershellgallery不一致？

### ISSUE THREAD

**Issue by pre1ude** [abgox/PSCompletions#24]
### 描述这个功能请求

https://www.powershellgallery.com/packages/PSCompletions/4.3.0
https://github.com/abgox/PSCompletions/releases/tag/v4.2.0
希望能在GitHub上同步更新最新的代码，谢谢

### 你正在使用什么 Powershell 版本?

Windows PowerShell

### 你正在使用什么系统环境?

Windows

**Comment by abgox** [comment]
- 模块在 github 的 releases 的版本不太重要，因为也不需要在 releases 下载模块，所以暂时是次版本在release 中发布
- 4.3.0 版本，在版本变更日志中有说明，实际上是 4.2.10 版本，只是为了避免模块内的版本号对比错误(对比错误已经在最新版本解决)
- 实际上所有的模块代码都是在仓库的 module 目录中，且一直保持最新

**Comment by pre1ude** [comment]
感谢解答，但是对于刚使用不了解的用户来说，可能会觉得代码版本发布不透明，而担心不敢升级
