### ISSUE TITLE
中文乱码，尤其是更新日志

### ISSUE THREAD

**Issue by QiE2035** [abgox/PSCompletions#3]
参考：<https://www.cnblogs.com/piapia/p/5452448.html>

![image](https://github.com/abgox/PSCompletions/assets/18079122/64e3509f-a84c-4b1d-b270-9300ab6ba23e)

**Comment by abgox** [comment]
经过我的测试，在我的电脑上正常。
估计可能是在下载和读取 log.json 出现了意外的编码解码错误。
如果仅仅只是更新日志的显示问题，它应该只是偶然的。
你可以直接通过 https://github.com/abgox/PSCompletions/blob/main/module/log.json 查看更新内容
![Snipaste_2023-12-13_10-19-31](https://github.com/abgox/PSCompletions/assets/131574323/4eb27fba-5cd9-435b-9cb0-d08dceb2f9fe)

**Comment by abgox** [comment]
我尝试使用了 Windows Powershell，确实存在下载的内容乱码的问题，我会尝试解决它

**Comment by abgox** [comment]
3.0.7版本已经发布，问题已经修复。
(修复从3.0.7开始生效，即在Windows Powershell 中，3.0.6更新到3.0.7的更新日志仍会乱码)
