### ISSUE TITLE
[Bug]: 补全框移动项目后显示不太正常

### ISSUE THREAD

**Issue by dyphire** [abgox/PSCompletions#37]
### 开始之前...

- [X] 你正在使用 PSCompletions 的最新版本。
- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经查看了 https://pscompletions.pages.dev/
- [X] 你已经在 [Issues](https://github.com/abgox/PSCompletions/issues) 中搜索相关问题。

### 你正在使用什么 Powershell 版本?

PowerShell

### 你正在使用什么系统环境?

Windows

### bug 复现步骤

使用 tab 补全功能显示补全框后尝试浏览列表

### 期望结果

补全框正确渲染

### 实际发生了什么?

补全框渲染异常
![image](https://github.com/user-attachments/assets/7668979a-59b2-481d-b660-7c7fe890454c)
![image](https://github.com/user-attachments/assets/330ecf0d-9bf1-4e33-880d-3be289616224)

**Comment by abgox** [comment]
- 你应该使用的是 Windows 系统内置的 `Windows PowerShell` 吧？
- `Windows PowerShell` 中确实可能出现这样的问题，因为 `Windows PowerShell` 本身就有一些渲染问题
- 建议使用 [`PowerShell`](https://github.com/PowerShell/PowerShell)，不要在使用 `Windows PowerShell` 了

**Comment by dyphire** [comment]
我使用的是 PowerShell 7，pswh

**Comment by abgox** [comment]
![image](https://github.com/user-attachments/assets/574acdef-b9a6-4c39-aa2e-c768e0c2fc2c)
- 在我这里就没有问题，你先清空你的 `$Profile` 文件，只导入 `PSCompletions` 试试？

**Comment by dyphire** [comment]
测试了下，发现是默认编码和输出文件编码在`Import-Module PSCompletions`前导致的，奇怪的兼容性问题
有可能优化吗？其他模块没遇到过

**Comment by abgox** [comment]
- https://pscompletions.pages.dev/FAQ
- 这个问题，我在 FAQ 中已经提到了
- 你只需要将 `Import-Module PSCompletions` 提前即可

**Comment by dyphire** [comment]
不止这一个影响，我测试了下把`Import-Module PSCompletions`放在其他模块下面一样会导致这种菜单渲染错误，它必须置于引入模块的第一个。确定不是兼容性问题吗？

**Comment by abgox** [comment]
- 我自己的 ` $Profile` 也有两三百行，我将 `Import-Module PSCompletions` 放到末尾，也都没有任何问题
- 主要其他人的  ` $Profile` 中，我也不知道到底放了些什么，可能也会存在一些冲突的模块
- 不过正常不会有兼容性问题，`PSCompletions` 模块也没有什么其他的依赖，只是使用了 `PowerShell` 内部的 `$Host` 对象，`Register-ArgumentCompleter` 和 `Set-PSReadLineKeyHandler`

**Comment by abgox** [comment]
> ~不止这一个影响，我测试了下把`Import-Module PSCompletions`放在其他`Import-Module`模块下面一样会导致这种菜单渲染错误，它必须置于引入模块的第一个。确定不是兼容性问题吗？~
> 
> 编辑：再次测试后发现是不能置于 oh-my-posh 模块下，没事了

应该不是这个问题，我一直都是将 `Import-Module PSCompletions` 这一行放在 `oh-my-posh init pwsh ...`  之后的

**Comment by dyphire** [comment]
> > ~不止这一个影响，我测试了下把`Import-Module PSCompletions`放在其他`Import-Module`模块下面一样会导致这种菜单渲染错误，它必须置于引入模块的第一个。确定不是兼容性问题吗？~
> > 编辑：再次测试后发现是不能置于 oh-my-posh 模块下，没事了
> 
> 应该不是这个问题，我一直都是将 `Import-Module PSCompletions` 这一行放在 `oh-my-posh init pwsh ...` 之后的

不是很清楚，主要我这边测试放在 oh-my-posh 模块下菜单渲染也会出错，我的`$Profile`总共也没多少配置
![image](https://github.com/user-attachments/assets/1f5d2c6f-1e3d-458a-8573-48e3184bdcd9)

**Comment by abgox** [comment]
- 原来你使用的是 oh-my-posh 这个 powershell 模块，我用的是 oh-my-posh 软件
- oh-my-posh 模块的话，它要渲染界面，我估计可能内部也修改了编码，所以才导致了渲染问题
- 反正，只要是修改了编码的，都必须放在 `PSCompletions` 后面，这样 `PSCompletions` 才可以获取到最开始的编码，从而不影响后续的渲染
- 这也不会影响其他模块，因为 `PSCompletions` 只会读取编码，不会修改编码

**Comment by dyphire** [comment]
习惯用 oh-my-posh 模块方式了，PowerShell 的配置文件夹通过 onedrive 同步，多设备使用方便些。反正问题已经解决了
