### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by liangzhenqiao** [abgox/PSCompletions#38]
### 开始之前...

- [X] 你正在使用 PSCompletions 的最新版本。
- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/PSCompletions/issues) 中搜索了相关问题。
- [X] 你已经查看了 https://pscompletions.pages.dev/

### 你正在使用什么 Powershell 版本?

PowerShell

### 你正在使用什么系统环境?

Windows

### bug 复现步骤

1、输入命令，空格，Tab键
2、提示信息排版显示问题，如截图
3、并且随着方向键向下选择，会进一步出现更糟糕的排版显示，并且会影响到正常的参数选择。

![Snipaste_2024-10-02_09-46-18](https://github.com/user-attachments/assets/ac83d5ff-db9c-492d-bab8-7011098104c2)

![Snipaste_2024-10-02_09-49-29](https://github.com/user-attachments/assets/4ce65617-4455-40b8-a827-f4b1683bcee3)

### 实际发生了什么?

1、输入命令，空格，Tab键
2、提示信息排版显示问题，如截图
3、并且随着方向键向下选择，会进一步出现更糟糕的排版显示，并且会影响到正常的参数选择。

![Snipaste_2024-10-02_09-46-18](https://github.com/user-attachments/assets/ac83d5ff-db9c-492d-bab8-7011098104c2)

![Snipaste_2024-10-02_09-49-29](https://github.com/user-attachments/assets/4ce65617-4455-40b8-a827-f4b1683bcee3)

**Comment by abgox** [comment]
- 看看这个 issue #11 
- 多半就是在导入 `PSCompletions` 之前修改了编码

**Comment by abgox** [comment]
- 如果也是修改了编码导致的问题，最简单的方式，就是把 `Import-Module PSCompletions` 这个导入语句直接放到配置文件的第一行

**Comment by liangzhenqiao** [comment]
> * 如果也是修改了编码导致的问题，最简单的方式，就是把 `Import-Module PSCompletions` 这个导入语句直接放到配置文件的第一行

的确是编码问题导致的。

昨天晚上我改了：控制面板--时钟和区域--选中beta, UTF8
![Snipaste_2024-10-02_10-13-14](https://github.com/user-attachments/assets/5f1e7da7-411e-4767-9d29-357929fb2951)

这样做的目的是为了让powershell输出到文档中的中文字符能够正常显示。

刚才我取消选中beta, UTF8之后，psc补全就正常显示了。

**Comment by abgox** [comment]
> 昨天晚上我改了：控制面板--时钟和区域--选中beta, UTF8

- 目前的情况是，不要启用这个 UTF8 beta
- 当启用它后，在 `Windows Terminal` 中对于中文的渲染就会有问题，主要是因为命令的中文帮助提示的渲染问题
- 如果因为一些原因必须启用这个 UTF8 beta，可以考虑以下几个解决方案
   -  如果不需要帮助提示，运行命令 `psc menu config enable_tip 0` 即可
   -  使用命令 `psc config language en-US` 将语言配置更改为英文，因为英文字符没有渲染问题，英文的帮助提示就可以正常渲染
   - 使用一些其他的终端外壳，目前来说，已知的 vscode 中的终端、Tabby、Hyper 都可以在启用这个 UTF8 beta 后正常使用
