### ISSUE TITLE
[Bug]: 导入PSCcompletions模块时报错

### ISSUE THREAD

**Issue by JHXs** [abgox/PSCompletions#41]
### 开始之前...

- [X] 你正在使用 PSCompletions 的最新版本。
- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/PSCompletions/issues) 中搜索了相关问题。
- [X] 你已经查看了 https://pscompletions.pages.dev/

### 你正在使用什么 Powershell 版本?

PowerShell

### 你正在使用什么系统环境?

Windows

### bug 复现步骤

使用scoop安装pwsh和PSCompletions 模块，安装好之后，输入Import-Module PSCompletions
系统版本：Win10 22h2 企业版
pwsh版本如下：
![图片](https://github.com/user-attachments/assets/4efba5af-ee9c-4c82-b314-48790d669e8e)

### 实际发生了什么?

我使用scoop安装pwsh和PSCompletions 模块，安装好之后，输入Import-Module PSCompletions得到如下输出：
![图片](https://github.com/user-attachments/assets/a82ff9f3-c568-4140-a754-8713dc3542fe)
我的$PROFILE文件如下：
![图片](https://github.com/user-attachments/assets/036d71ef-d935-4460-b165-526b6b9450b6)
根据报错显示的是init.ps1第1231和1233行运行错误，请问这个怎么解决，谢谢！

### 还有其他你想要补充的信息吗？

使用Install-Module PSCompletions -Scope CurrentUser安装模块再导入也报错

**Comment by abgox** [comment]
- 你应该不是安装的 [abgo_bucket](https://github.com/abgox/abgo_bucket) 这个 scoop bucket 中的 `PSCompletions` 吧
- 其他人写的应用清单可能不完整，导致报错，最好使用我提供的应用清单安装
- 不过这个问题会在下一个版本 `5.0.7` 中修复
