### ISSUE TITLE
[Bug]: emoji/text rendering issue

### ISSUE THREAD

**Issue by flatlined** [abgox/PSCompletions#49]
### Before Start

- [X] You are using the latest version of PSCompletions.
- [X] You have read this repository's README file.
- [X] You have search for related issues in [Issues](https://github.com/abgox/PSCompletions/issues).
- [X] You have visit https://pscompletions.pages.dev/

### What Powershell version are you using?

PowerShell

### What system are you using?

Windows

### Steps to reproduce

Install psc, import it, open the menu

### What is expected?

Proper rendering if all text / glyphs.

### What is actually happening?

![image](https://github.com/user-attachments/assets/b53b32b5-6dd9-4730-8385-9c181fb8457c)
Text characters render normally. Emoji and other glyphs do not.

### Any additional comments?

The Beta option in Regional Settings in the Control Panel is not checked.
Emoji do render normally in the terminal, but not in the psc menu.
I have tried this with my full Powershell profile (as seen in the image above), with an empty profile except for `Import-Module PSCompletions`, and with an empty profile except for 
```
Import-Module PSCompletions
$OutputEncoding = [console]::InputEncoding = [console]::OutputEncoding = New-Object System.Text.UTF8Encoding
```
or 
```
$OutputEncoding = [console]::InputEncoding = [console]::OutputEncoding = New-Object System.Text.UTF8Encoding
Import-Module PSCompletions
```
but all variations fail to render emoji properly.

**Comment by abgox** [comment]
- Are you using `Windows Terminal Preview`?
- There is a rendering problem in `Windows Terminal Preview`, but it works fine in `Windows Terminal`
- It probably a bug in `Windows Terminal Preview`.

![image](https://github.com/user-attachments/assets/59297a9d-b7fb-43d5-a68b-5476fe82663d)

**Comment by abgox** [comment]
> $OutputEncoding = [console]::InputEncoding = [console]::OutputEncoding = New-Object System.Text.UTF8Encoding

- Actually, the output encoding problem only exists in `Windows Terminal (Preview)`, other terminal tools like `Tabby`, `Hyper` don't have rendering issues.

**Comment by abgox** [comment]
- It's a bug in `Windows Terminal Preview`, I'll open an issue in the [terminal repository](https://github.com/microsoft/terminal) and wait for a fix.
- Now, you can try to customize it to other available characters.

**Comment by abgox** [comment]
https://github.com/microsoft/terminal/issues/18242

**Comment by abgox** [comment]
#53
