### ISSUE TITLE
[Request]: Documentation on how to update the module

### ISSUE THREAD

**Issue by tobiasdiez** [abgox/PSCompletions#52]
### Describe the request

Completions one can update via `psc update *`, but how does one update the module itself?

### What Powershell version are you using?

PowerShell

### What system are you using?

Windows

### Any additional comments?

If you have outdated completions, it says
```
If you don't want to see it, you can hide it by running psc config update 0
```

but it should be `psc config enable_completions_update 0`, I think.

--

Thanks for the awesome module!

**Comment by abgox** [comment]
This is an outdated help message, I'll fix it.

**Comment by abgox** [comment]
- It will be fixed with the next module version.
- You can also use `psc update psc` to fix it now.

**Comment by abgox** [comment]
- It may be a network problem.
- It may be a problem with the `PSCompletions` module itself.
- Try the latest module version 5.2.1 now, if you haven't updated yet.
- In the `v5.2.1` , you can use `psc update * --force` to force update all completions, including `psc`.
