### ISSUE TITLE
[Request]: 允许使用 Update-PSResource 来升级模块

### ISSUE THREAD

**Issue by frg2089** [abgox/PSCompletions#54]
### 描述这个功能请求

允许使用 `Update-PSResource` cmdlet 来升级模块

有些用户（对 就是我）会使用 `Install-PSResource` cmdlet 而不是 `Install-Module` 函数来安装模块 这种时候使用`Update-Module` 函数会提示未安装模块导致升级失败

添加一个配置项以允许使用 `Update-PSResource` 来升级模块

> [!NOTE]
> Microsoft.PowerShell.PSResourceGet 是 PowerShell 的新包管理解决方案。
> 引自[微软文档](https://learn.microsoft.com/powershell/gallery/powershellget/install-powershellget?view=powershellget-3.x#install-microsoftpowershellpsresourceget)

### 你正在使用什么 Powershell 版本?

PowerShell

### 你正在使用什么系统环境?

Windows

### 还有其他你想要补充的信息吗？

https://github.com/abgox/PSCompletions/blob/893435b96eee5234e712fe7cb7ec3bbc3bda0fdc/module/PSCompletions/core/init.ps1#L1342
```pwsh
Update-PSResource -Name PSCompletions -Repository PSGallery -TrustRepository
```

[PowerShell 的包管理](https://learn.microsoft.com/zh-cn/powershell/gallery/powershellget/overview)

<details>
<summary>没啥用的严谨</summary>

![image](https://github.com/user-attachments/assets/454b363f-a946-4a29-9444-1b2f413e58ec)

</details>

**Comment by abgox** [comment]
- 相关 commit: https://github.com/abgox/PSCompletions/commit/79095e7691e82e0fd85b18bd0af022cc62861399
- 下个版本添加
- 从下个版本更新到下下个版本时才起效
