### ISSUE TITLE
[Request]: 取消更新时要求键盘输入

### ISSUE THREAD

**Issue by ycna07** [abgox/PSCompletions#59]
### 描述这个功能请求

去除启动时更新提示要求的键盘输入
在使用vscode集成终端直接运行代码时，vscode的键盘输入会被打断而导致无法运行
![image](https://github.com/user-attachments/assets/3682e74c-a73a-42cf-8d4e-44c8a1e65b83)

### 你正在使用什么 Powershell 版本?

PowerShell7.4.6

### 你正在使用什么系统环境?

Windows11 27749

### 还有其他你想要补充的信息吗？

无

**Comment by abgox** [comment]
- 遇到有更新确认的情况，你应该首先确认更新，然后再去运行其他命令
- 或者，直接禁用更新检查 `psc config enable_module_update 0`
