### ISSUE TITLE
无法补全带有程序后缀名的命令

### ISSUE THREAD

**Issue by Arama-Vanarana** [abgox/PSCompletions#8]
例如:
```PowerShell
# 补全为.\xxx
scoop.ps1 <Tab>
# 正常
scoop <Tab>
```
因为PowerShell在补全scoop(并非只有scoop)时会自动补全为scoop.cmd或scoop.ps1, 希望能解决一下(谢谢大佬了)

**Comment by abgox** [comment]
- 如果是因为觉得像 `scoop` 这样的命令过长，使用 `Tab` 导致补全为 `scoop.ps1`
- 你应该像 `psc alias add scoop sc`  这样去设置简洁的别名
- 需要注意的是，这里设置的不止是补全触发的别名，同时也是命令本身(如 `scoop`)的别名

**Comment by Arama-Vanarana** [comment]
emmm好吧

**Comment by abgox** [comment]
- 目前，`PSCompletions` 已经到了 `v5.2.1`
- 别名已经更改为了别名列表，可以添加多个
- 使用 `psc alias add scoop scoop.ps1 scoop.cmd` 即可

> 这个回复是为了给出实现方法，供后续可能访问此 issue 的人提供参考
