### ISSUE TITLE
scoop download -h参数错误

### ISSUE THREAD

**Issue by Arama-Vanarana** [abgox/PSCompletions#9]
-h参数为help而不是--no-hash-check
![屏幕截图 2024-03-05 042600](https://github.com/abgox/PSCompletions/assets/122252361/a72b9936-fb16-496c-ba85-d5dbe36e69f2)

**Comment by Arama-Vanarana** [comment]
![屏幕截图 2024-03-05 042704](https://github.com/abgox/PSCompletions/assets/122252361/54b07941-933f-45c1-8dfd-8dab415c0643)

**Comment by abgox** [comment]
- 这似乎是官方帮助说明对于此参数的错误简写
- 既然与帮助重名，就直接使用 `--no-hash-check` 不使用简写了
